### ISSUE TITLE
Repository link on npm is out of date

### ISSUE THREAD

**Issue by hypesystem** [qualweb/qualweb#225]
The npm package for e.g. [qualweb/core](https://www.npmjs.com/package/@qualweb/core) links to the git repo before this was merged into a monorepo.

Happy to supply a PR if you are open to it.

**Comment by carlosapaduarte** [comment]
Thanks for spotting it! 

Happy for you to submit a PR

**Comment by Tellus** [comment]
New packages released with corrected URLs. Closing as fixed.

Thanks for raising the issue!
