### ISSUE TITLE
@qualweb/act-rules: QW-ACT-R7 fails test case for "Failed example 4"

### ISSUE THREAD

**Issue by Tellus** [qualweb/qualweb#68]
Hey guys,

QW-ACT-R7 fails to run for the test case "Failed example 4".

I don't know if we should have an issue for each of the currently failing test cases (currently, R4, R12, R29, R34, R36, R58, R59, R62, and R71 also have problems) or a big "fixing test cases" issue for picking up the missing parts for implementation conformance.

**Comment by carlosapaduarte** [comment]
I would go with one issue for each failing test case and use a common label to group them (just added one for that)
