### ISSUE TITLE
@qualweb/act-rules: QW-ACT-R15 - Audio or video element avoids automatically playing audio (80f0bf)

### ISSUE THREAD

**Issue by carlosapaduarte** [qualweb/qualweb#96]
[Audio or video element avoids automatically playing audio](https://www.w3.org/WAI/standards-guidelines/act/rules/80f0bf/proposed/#implementations)

**Comment by Tellus** [comment]
Just ran a fresh set of tests, and only R4 and R71 is failing now. Can we safely close this issue?
